language: python
python:
  - "2.7"
notifications:
  email: false

virtualenv:
  system_site_packages: true
  
install:
  - pip install --use-mirrors matplotlib

before_install:
  - pip install numpy
  - pip install scipy
 
script:
  - python curve_fitting_test.py
  - python weeks_processor_test.py
