language: python
python:
  - "2.7"
notifications:
  email: false

virtualenv:
  system_site_packages: true
  
install:
  - "pip install -r requirements.txt --use-mirrors"

before_install:
  - sudo apt-get install -qq python-numpy python-scipy
 
script:
  - python curve_fitting_test.py
  - python weeks_processor_test.py
