language: python
python:
  - "2.7"
notifications:
  email: false

virtualenv:
  system_site_packages: true

before_install:
  - wget https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz
  - tar -xvzf protobuf-2.5.0.tar.gz
  - cd protobuf-2.5.0
  - ./configure && sudo make install
  - cd python
  - python setup.py build
  - sudo python setup.py install
  - cd ../..
  - pip install matplotlib
  - sudo apt-get -qq update
  - sudo apt-get -qq install python-numpy python-scipy python-tk

script:
  - python curve_fitting_test.py
  - python weeks_processor_test.py
  - ./single_symbol_test.sh
  - ./multiple_symbols_test.sh
