application: deep-trading
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /cron/weekly_best_stocks_report
  script: weekly_best_stocks.application
- url: /cron/weekly_best_stocks_process
  script: weekly_best_stocks.application
- url: /.*
  script: deep-trading.application

libraries:
- name: numpy
  version: "latest"
  
builtins:
- deferred: on
