runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /cron/weekly_best_stocks_report
  script: weekly_best_stocks_report.application
  login: admin
- url: /cron/weekly_best_stocks_process
  script: weekly_best_stocks_process.application
  login: admin
- url: /.*
  script: deep-trading.application
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

libraries:
 - name: numpy
   version: "latest"

builtins:
- deferred: on
- remote_api: on
